version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      # - <port on localhost>:<port on container> transfer from localhost port to container port
      - 8080:8000
    volumes:
      - ./:/usr/src/app:ro    # syncing current folder in docker container, so that when we make any changes in current folder, it reflects in docker container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload    # overwriting Dockerfile
    # env_file:
    #   - ./.env
    environment:
      # - DATABASE_HOSTNAME = localhost
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Abhishek2710
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Abhishek2710
      - POSTGRES_DB=fastapi
    
    volumes:                # Save the data when container is down
      - postgres-db:/var/lib/postgresql/data    # path in the container

volumes:
  postgres-db: